theme: osuny
_merge: deep
params:
  search:
    active: false
  logo:
    # Handle logo in darkmode with this configuration
    header: "/assets/images/zinefest-12.png"
      # default: "/assets/images/logo.png"
      # darkmode: "/assets/images/logo-white.png"
    footer: "/assets/images/dealer-vecto-color.png"
      # default: "/assets/images/star.png"
      # darkmode: "/assets/images/star.png"
  breadcrumb:
    position: none #  hero-start |  hero-end | after-hero | none
  summary:
    position: content # hero | content
  events:
    default_image: true
    date_format: ":date_long"
    index:
      show_categories: false
      show_author: false
      show_description: false
      truncate_description: 200 # Set to 0 to disable truncate
      layout: grid # grid | list
  organizations:
    dark_logo_background: false
    map_marker_icon: '/assets/images/markerdealer.png'
  image_sizes:
    design_system:
      lightbox:
        disabled: true
    sections:
      home:
        hero:
          mobile:   800
          tablet:   2000
          desktop:  2000
      pages:
        hero:
          mobile:   100
          tablet:   100
          desktop:  100
      events:
        hero:
          mobile:   100
          tablet:   100
          desktop:  100
        hero_single:
          mobile:   700
          tablet:   940
          desktop:  500
        item:
          mobile:   700
          tablet:   450
          desktop:  500
    blocks:
      organizations:
        mobile:   300
        tablet:   300
        desktop:  300