theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  search:
    active: false  
  logo:
    # Handle logo in darkmode with this configuration
    header: "/assets/images/logo.png"
      # default: "/assets/images/logo.png"
      # darkmode: "/assets/images/logo-white.png"
    footer: "/assets/images/star.png"
      # default: "/assets/images/star.png"
      # darkmode: "/assets/images/star.png"
  breadcrumb:
    position: none #  hero-start |  hero-end | after-hero | none
  summary:
    position: content # hero | content
  events:
    default_image: true
    date_format: ":date_long"
    index:
      show_categories: false
      show_author: false
      show_description: false
      truncate_description: 200 # Set to 0 to disable truncate
      layout: grid # grid | list
  organizations:
    dark_logo_background: false
    map_marker_icon: '/assets/images/markerdealer.png'
  image_sizes:
    design_system:
      lightbox:
        disabled: true
    sections:
      home:
        hero:
          mobile:   800
          tablet:   800
          desktop:  750
        