[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/agenda/archives/index.html"
to = "/evenements/archives/"

[[redirects]]
from = "/exposantes/index.html"
to = "/invites/"

[[redirects]]
from = "/invites-et-partenaires/les-lilas-boris-dugland-detraz/index.html"
to = "/invites-et-partenaires/les-lilas-boris-detraz/"

[[redirects]]
from = "/organisations/fripouilles/index.html"
to = "/invites-et-partenaires/fripouilles/"

[[redirects]]
from = "/2024/08/index.html"
to = "/evenements/2024/08/"

[[redirects]]
from = "/organisations/partenaire/index.html"
to = "/invites-et-partenaires/categories/partenaire/"

[[redirects]]
from = "/categories/exposant-e/index.html"
to = "/invites-et-partenaires/categories/exposant-e/"

[[redirects]]
from = "/archives-expositions/index.html"
to = "/expositions/archives-expositions/"

[[redirects]]
from = "/organisations/arthur-plateau-chats-noirs/index.html"
to = "/invites-et-partenaires/arthur-plateau/"

[[redirects]]
from = "/evenements/2024-07-03-test/index.html"
to = "/evenements/2024/atelier-fanzine-collectif/"

[[redirects]]
from = "/evenements/2024-07-05-lancement-et-exposition-musique-du-diable-iii/index.html"
to = "/evenements/2024/lancement-et-exposition-musique-du-diable-iii/"

[[redirects]]
from = "/n-a-qu-1-oeil/index.html"
to = "/invites-et-partenaires/n-a-qu-1-oeil/"

[[redirects]]
from = "/organisations/chasse-goupille/index.html"
to = "/invites-et-partenaires/chasse-goupille/"

[[redirects]]
from = "/organisations/grante-egle/index.html"
to = "/invites-et-partenaires/grante-egle/"

[[redirects]]
from = "/organisations/ville-de-bordeaux/index.html"
to = "/invites-et-partenaires/ville-de-bordeaux/"

[[redirects]]
from = "/organisations/gazzeta-ultra/index.html"
to = "/invites-et-partenaires/gazzeta-ultra/"

[[redirects]]
from = "/organisations/collectif-sapin/index.html"
to = "/invites-et-partenaires/collectif-sapin/"

[[redirects]]
from = "/organisations/editions-adverse/index.html"
to = "/invites-et-partenaires/editions-adverse/"

[[redirects]]
from = "/organisations/drac-nouvelle-aquitaine/index.html"
to = "/invites-et-partenaires/drac-nouvelle-aquitaine/"

[[redirects]]
from = "/2024/salon-de-micro-editions-fanzines-et-multiples/index.html"
to = "/evenements/2024/salon-de-micro-editions-fanzines-et-multiples/"

[[redirects]]
from = "/2024/12/index.html"
to = "/evenements/2024/12/"

[[redirects]]
from = "/evenements/2024-07-06-salon-de-micro-editions-fanzines-et-multiples/index.html"
to = "/evenements/2024/salon-de-micro-editions-fanzines-et-multiples/"

[[redirects]]
from = "/2024/soiree-concerts/index.html"
to = "/evenements/2024/soiree-concerts/"

[[redirects]]
from = "/2024/lancement-et-exposition-musique-du-diable-iii/index.html"
to = "/evenements/2024/lancement-et-exposition-musique-du-diable-iii/"

[[redirects]]
from = "/organisations/disparate/index.html"
to = "/invites-et-partenaires/disparate/"

[[redirects]]
from = "/drac-nouvelle-aquitaine/index.html"
to = "/invites-et-partenaires/drac-nouvelle-aquitaine/"

[[redirects]]
from = "/evenements/2024-07-03-vernissage-de-lexposition-rondo-de-palefroi/index.html"
to = "/evenements/2024/vernissage-de-lexposition-rondo-de-palefroi/"

[[redirects]]
from = "/2024/01/index.html"
to = "/evenements/2024/01/"

[[redirects]]
from = "/evenements/2024-06-29-atelier-fanzine-collectif/index.html"
to = "/evenements/2024/atelier-fanzine-collectif/"

[[redirects]]
from = "/2024/02/index.html"
to = "/evenements/2024/02/"

[[redirects]]
from = "/2024/ateliers-de-pratique-artistique/index.html"
to = "/evenements/2024/ateliers-de-pratique-artistique/"

[[redirects]]
from = "/organisations/aux-enfants-du-talus/index.html"
to = "/invites-et-partenaires/aux-enfants-du-talus/"

[[redirects]]
from = "/la-halle-des-douves/index.html"
to = "/invites-et-partenaires/la-halle-des-douves/"

[[redirects]]
from = "/organisations/adele-frost/index.html"
to = "/invites-et-partenaires/adele-frost/"

[[redirects]]
from = "/2024/05/index.html"
to = "/evenements/2024/05/"

[[redirects]]
from = "/evenements/2024-07-04-ateliers-de-pratique-artistique/index.html"
to = "/evenements/2024/ateliers-de-pratique-artistique/"

[[redirects]]
from = "/organisations/palefroi/index.html"
to = "/invites-et-partenaires/palefroi/"

[[redirects]]
from = "/organisations/free-hands-fanzine/index.html"
to = "/invites-et-partenaires/cellophane-micro-edition-free-hands-fanzine/"

[[redirects]]
from = "/categories/partenaire/index.html"
to = "/invites-et-partenaires/categories/partenaire/"

[[redirects]]
from = "/2024/09/index.html"
to = "/evenements/2024/09/"

[[redirects]]
from = "/invites-et-partenaires/exposant-e/index.html"
to = "/invites-et-partenaires/categories/exposant-e/"

[[redirects]]
from = "/2024/vernissage-de-lexposition-rondo-de-palefroi/index.html"
to = "/evenements/2024/vernissage-de-lexposition-rondo-de-palefroi/"

[[redirects]]
from = "/la-fabrique-pola/index.html"
to = "/invites-et-partenaires/la-fabrique-pola/"

[[redirects]]
from = "/evenements/2024-07-05-test/index.html"
to = "/evenements/2024/atelier-fanzine-collectif/"

[[redirects]]
from = "/organisations/editions-microgram/index.html"
to = "/invites-et-partenaires/editions-microgram/"

[[redirects]]
from = "/agenda/index.html"
to = "/evenements/"

[[redirects]]
from = "/invites-et-partenaires/linsoleuse/index.html"
to = "/invites-et-partenaires/l-insoleuse/"

[[redirects]]
from = "/2024/03/index.html"
to = "/evenements/2024/03/"

[[redirects]]
from = "/organisations/chloe-cavalier/index.html"
to = "/invites-et-partenaires/chloe-cavalier/"

[[redirects]]
from = "/organisations/du-noir-sous-les-ongles/index.html"
to = "/invites-et-partenaires/du-noir-sous-les-ongles/"

[[redirects]]
from = "/invites-et-partenaires/partenaire/index.html"
to = "/invites-et-partenaires/categories/partenaire/"

[[redirects]]
from = "/evenements/2024-07-06-street-party/index.html"
to = "/evenements/2024/street-party/"

[[redirects]]
from = "/organisations/exposant-e/index.html"
to = "/invites-et-partenaires/categories/exposant-e/"

[[redirects]]
from = "/organisations/adelepetitfeu/index.html"
to = "/invites-et-partenaires/adelepetitfeu/"

[[redirects]]
from = "/2024/10/index.html"
to = "/evenements/2024/10/"

[[redirects]]
from = "/2024/04/index.html"
to = "/evenements/2024/04/"

[[redirects]]
from = "/2024/11/index.html"
to = "/evenements/2024/11/"

[[redirects]]
from = "/2024/06/index.html"
to = "/evenements/2024/06/"

[[redirects]]
from = "/2024/street-party/index.html"
to = "/evenements/2024/street-party/"

[[redirects]]
from = "/2024/index.html"
to = "/evenements/2024/"

[[redirects]]
from = "/organisations/la-fabrique-pola/index.html"
to = "/invites-et-partenaires/la-fabrique-pola/"

[[redirects]]
from = "/evenements/2024-07-04-soiree-concerts/index.html"
to = "/evenements/2024/soiree-concerts/"

[[redirects]]
from = "/organisations/index.html"
to = "/invites-et-partenaires/"

[[redirects]]
from = "/2024/atelier-fanzine-collectif/index.html"
to = "/evenements/2024/atelier-fanzine-collectif/"

[[redirects]]
from = "/invites-et-partenaires/arthur-plateau-chats-noirs/index.html"
to = "/invites-et-partenaires/arthur-plateau/"

[[redirects]]
from = "/evenements/2024-07-07-salon-de-micro-editions-fanzines-et-multiples-1/index.html"
to = "/evenements/2024/salon-de-micro-editions-fanzines-et-multiples-1/"

[[redirects]]
from = "/organisations/alice-monvaillier/index.html"
to = "/invites-et-partenaires/alice-monvaillier/"

[[redirects]]
from = "/l-insoleuse/index.html"
to = "/invites-et-partenaires/l-insoleuse/"

[[redirects]]
from = "/organisations/atelier-temeraire/index.html"
to = "/invites-et-partenaires/atelier-temeraire/"

[[redirects]]
from = "/invites-et-partenaires/post-fire-books/index.html"
to = "/invites-et-partenaires/postfirebooks/"

[[redirects]]
from = "/2024/07/index.html"
to = "/evenements/2024/07/"

[[redirects]]
from = "/evenements/2024-06-29-test/index.html"
to = "/evenements/2024/atelier-fanzine-collectif/"

